### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ghost** [Daniel-Khodabakhsh/datetime-format#1]
Hello, thank you for this extension, however it doesn't install.

**1)** Warning about remote HEAD during git clone
```
git clone https://github.com/Daniel-Khodabakhsh/datetime-format.git
Clonage dans 'datetime-format'...
remote: Counting objects: 34, done.
remote: Total 34 (delta 0), reused 0 (delta 0), pack-reused 34
Dépaquetage des objets: 100% (34/34), fait.
Vérification de la connectivité... fait.
warning: la HEAD distante réfère à une référence non existante, impossible de l'extraire.
```

**2)** Error about missing module during node build
```
node build.js
module.js:471
    throw err;
    ^
Error: Cannot find module '/home/alex.dws/Téléchargements/_autres/datetime-format/build.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by ghost** [comment]
I had the same problem. After cloning the repo, you should run `git checkout release`. This should be added to the installation instructions.

**Comment by ghost** [comment]
Thank you, it works with this method :)

PS: I'm sorry, title for this issue was kinda confusing, it doesn't install using instructions here, but of course this extension works well using extensions website.

**Comment by Daniel-Khodabakhsh** [comment]
Hey @DarthWound 

Sorry for the late reply, I was on vacation until today.

I'll update the installation instructions with @Ryan8781's suggestion. Thanks for that!

**Comment by Daniel-Khodabakhsh** [comment]
Fixed in https://github.com/Daniel-Khodabakhsh/datetime-format/commit/9773e7682dc81a7e953762ac9c90f03e6c34ef45.
