### ISSUE TITLE
Gnome 42.4

### ISSUE THREAD

**Issue by lonix1** [Daniel-Khodabakhsh/datetime-format#24]
just upgraded to ubuntu 22.04
`gnome-shell --version` = 42.4

This extension stopped working:
> TypeError: extension.imports.Settings.Class is not a constructor

Anyone have a fix, or an alternative?

**Comment by jumpnett** [comment]
I'm currently using [Panel Date Format](https://extensions.gnome.org/extension/1462/panel-date-format/) instead, since this one hasn't been updated.
